[package]
name = "trident"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
bitpacking = "0.8.4"
fnv = "1.0.7"
hashers = "1.0.1"
histogram = "0.6.9"
integer-encoding = "3.0.4"
quickcheck = "1.0.3"
rand = "0.8.5"
walkdir = "2.3.2"

[profile.release]
debug = true
