[package]
name = "trident"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
bitpacking = "0.8.4"
fnv = "1.0.7"
hashers = "1.0.1"
memmap2 = "0.5.7"
mmap-allocator = "0.3.1"
simdutf8 = "0.1.4"
varint-rs = "2.2.0"
walkdir = "2.3.2"

[profile.release]
debug = true
